{
 "title": "Airflow & Datalake",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "MongoDB CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".*mongo.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "MongoDB Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".*mongo.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Logs Volume per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (job) (count_over_time({job=\"airflow_logs\"} [$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"airflow_logs\"} |= \"error\""
    }
   ]
  },
  {
   "title": "Airflow Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"airflow_logs\"}"
    }
   ]
  }
 ]
}